'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _templateObject = _taggedTemplateLiteral(['\n  .DayPickerNavigation__prev,\n  .DayPickerNavigation__next {\n    cursor: pointer;\n    user-select: none;\n    text-align: center;\n    width: 30px;\n    height: 30px;\n    line-height: 30px;\n  }\n\n  .DayPickerNavigation__prev--disabled,\n  .DayPickerNavigation__next--disabled {\n    cursor: default;\n    opacity: .2;\n    pointer-events: none;\n  }\n\n  .DayPickerNavigation__prev--default,\n  .DayPickerNavigation__next--default {}\n\n  .DayPickerNavigation--horizontal {\n    position: relative;\n\n    .DayPickerNavigation__prev,\n    .DayPickerNavigation__next {\n      top: 18px;\n      z-index: 2;\n      position: absolute;\n    }\n\n    .DayPickerNavigation__prev {\n      left: 22px;\n    }\n\n    .DayPickerNavigation__next {\n      right: 22px;\n    }\n  }\n\n  .DayPickerNavigation--vertical {\n    position: absolute;\n    bottom: 0;\n    left: 0;\n    height: 52px;\n    width: 100%;\n    z-index: 2;\n\n    .DayPickerNavigation__prev,\n    .DayPickerNavigation__next {\n      display: inline-block;\n      position: relative;\n      height: 100%;\n      width: 50%;\n    }\n\n    .DayPickerNavigation__next--default {\n      border-left: 0;\n    }\n  }\n\n  .DayPickerNavigation--vertical-scrollable {\n    position: relative;\n\n    .DayPickerNavigation__next {\n      width: 100%;\n    }\n  }\n'], ['\n  .DayPickerNavigation__prev,\n  .DayPickerNavigation__next {\n    cursor: pointer;\n    user-select: none;\n    text-align: center;\n    width: 30px;\n    height: 30px;\n    line-height: 30px;\n  }\n\n  .DayPickerNavigation__prev--disabled,\n  .DayPickerNavigation__next--disabled {\n    cursor: default;\n    opacity: .2;\n    pointer-events: none;\n  }\n\n  .DayPickerNavigation__prev--default,\n  .DayPickerNavigation__next--default {}\n\n  .DayPickerNavigation--horizontal {\n    position: relative;\n\n    .DayPickerNavigation__prev,\n    .DayPickerNavigation__next {\n      top: 18px;\n      z-index: 2;\n      position: absolute;\n    }\n\n    .DayPickerNavigation__prev {\n      left: 22px;\n    }\n\n    .DayPickerNavigation__next {\n      right: 22px;\n    }\n  }\n\n  .DayPickerNavigation--vertical {\n    position: absolute;\n    bottom: 0;\n    left: 0;\n    height: 52px;\n    width: 100%;\n    z-index: 2;\n\n    .DayPickerNavigation__prev,\n    .DayPickerNavigation__next {\n      display: inline-block;\n      position: relative;\n      height: 100%;\n      width: 50%;\n    }\n\n    .DayPickerNavigation__next--default {\n      border-left: 0;\n    }\n  }\n\n  .DayPickerNavigation--vertical-scrollable {\n    position: relative;\n\n    .DayPickerNavigation__next {\n      width: 100%;\n    }\n  }\n']);

var _styledComponents = require('styled-components');

function _taggedTemplateLiteral(strings, raw) { return Object.freeze(Object.defineProperties(strings, { raw: { value: Object.freeze(raw) } })); }

exports.default = (0, _styledComponents.css)(_templateObject);